package com.github.amberdemon.paymentservice.model;

public enum SchemePaymentType {
IMMEDIATEPAYMENT,
FORWARDDATEDPAYMENT,
STANDINGORDER,
BULKAUTHORISATION,
SCHEMERETURNPAYMENT,
CORPORATEBULKPAYMENT,
RECALL,
RETURNCREDIT,
CLAIMFORUNPAIDCHEQUE,
AUTOMATESETTLEMENT,
ARUDDFIRSTCOLLECTION,
ARUDDREGULARCOLLECTION,
ARUDDREPRESENTED,
ARUDDFINALCOLLECTION
}
